services:
  - type: web
    name: core-users-api
    runtime: node
    buildCommand: NODE_ENV=development npm ci && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
